import os
import subprocess
import sys
import fitz  # PyMuPDF
from dotenv import load_dotenv

def generate_dummy_pdf(output_path):
    doc = fitz.open()
    page = doc.new_page()
    text = """The Pre-Salt carbonate reservoirs of the Santos Basin are composed of microbialites and coquinas.
Faults and fractures generated by rifting control the porosity.
Diagenesis plays a major role in reservoir quality."""
    
    # Insert text
    page.insert_text((50, 50), text, fontsize=12)
    doc.save(output_path)
    doc.close()
    print(f"Generated dummy PDF at: {output_path}")

def run_test():
    # Load test environment variables
    # We use stream=True to avoid polluting the current process too much, 
    # but constructing a fresh env dict for the subprocess is better.
    
    # 1. Read existing env (to keep PATH, etc.)
    # Based on new location (test/), real .env is in ../.env
    load_dotenv(os.path.join(os.path.dirname(__file__), "../.env")) 
    env = os.environ.copy()
    
    # Check if key exists
    if not env.get("GEMINI_API_KEY"):
         print("WARNING: GEMINI_API_KEY not found in environment or ../.env!")

    # 2. Load .env-test manually to override
    print("Loading test configuration...")
    test_env_path = os.path.join(os.path.dirname(__file__), ".env-test")
    with open(test_env_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, val = line.split("=", 1)
            # Handle variable expansion if needed (simplistic here)
            if val == "${GEMINI_API_KEY}":
                val = os.environ.get("GEMINI_API_KEY", "")
            
            env[key] = val
            
    # Verify critical vars
    print(f"Test Configuration:")
    print(f"  DOCS_DIR: {env.get('DOCS_DIR')}")
    print(f"  LLM_INPUT_DIR: {env.get('LLM_INPUT_DIR')}")
    print(f"  OUTPUT: {env.get('LLM_OUTPUT_FILE')}")

    # Setup Paths
    base_test_dir = os.path.dirname(os.path.abspath(__file__))
    inputs_dir = os.path.join(base_test_dir, "inputs_test")
    os.makedirs(inputs_dir, exist_ok=True)
    
    # Generate Input PDF only if it doesn't exist
    pdf_path = os.path.join(inputs_dir, "test_doc.pdf")
    if not os.path.exists(pdf_path):
        generate_dummy_pdf(pdf_path)
    else:
        print(f"Using existing test PDF: {pdf_path}")
    
    # 3. Clean previous test outputs (paths are relative to ROOT because of env var config, but we are running delete here)
    # We should interpret paths relative to ROOT for consistency.
    subprocess.run("rm -rf test/output_test/* test/chroma_db_test", shell=True, cwd="..")
    
    # Clean legacy MD file if exists to ensure PDF conversion is tested
    subprocess.run("rm -f test/inputs_test/*.md", shell=True, cwd="..")
    
    # 4. Run Pipeline as subprocess from ROOT
    print("\nRunning pipeline subprocess...")
    # We execute from parent directory so pipeline.py can verify imports
    result = subprocess.run(
        [sys.executable, "pipeline.py"], 
        env=env,
        cwd=os.path.join(os.path.dirname(__file__), ".."), # Run from root
        capture_output=False 
    )
    
    if result.returncode != 0:
        print("\n❌ Pipeline failed!")
        sys.exit(result.returncode)
        
    # 5. Assetions
    print("\n✅ Pipeline execution finished. Verifying artifacts...")
    
    # Artifacts are in test/output_test/ (relative to ROOT)
    expected_files = [
        "test/output_test/1_raw_llm_extraction.json",
        "test/output_test/2_aggregated_counts.csv",
        "test/output_test/3_filtered_top_terms.csv",
        "test/output_test/4_nld_generated_definitions.csv",
        "test/output_test/5_categorized_ontology.csv"
    ]
    
    all_passed = True
    # Check assertions from ROOT perspective or adjust path
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # test/..
    
    for f in expected_files:
        full_path = os.path.join(root_dir, f)
        if os.path.exists(full_path):
            # Optional: Check size > 0
            if os.path.getsize(f) > 0:
                print(f"  [OK] Found {f}")
            else:
                print(f"  [WARN] Found {f} but it is empty")
        else:
            print(f"  [FAIL] Missing {f}")
            all_passed = False
            
    if all_passed:
        print("\n🎉 E2E Test Passed Successfully!")
    else:
        print("\n❌ E2E Test Failed: Missing artifacts.")
        sys.exit(1)

if __name__ == "__main__":
    run_test()
