import csv
import os
import subprocess
import sys
import fitz  # PyMuPDF
from dotenv import load_dotenv


def generate_dummy_pdf(output_path):
    doc = fitz.open()
    page = doc.new_page()
    text = """The Pre-Salt carbonate reservoirs of the Santos Basin are composed of microbialites and coquinas.
Faults and fractures generated by rifting control the porosity.
Diagenesis plays a major role in reservoir quality."""

    # Insert text
    page.insert_text((50, 50), text, fontsize=12)
    doc.save(output_path)
    doc.close()
    print(f"Generated dummy PDF at: {output_path}")


def validate_csv(filepath, expected_columns, min_rows=1, label=""):
    """Validate a CSV file has expected columns and minimum row count."""
    errors = []
    try:
        with open(filepath, "r", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            headers = reader.fieldnames or []

            # Check expected columns
            missing_cols = set(expected_columns) - set(headers)
            if missing_cols:
                errors.append(f"Missing columns: {missing_cols}")

            # Count data rows and basic checks
            rows = list(reader)
            if len(rows) < min_rows:
                errors.append(f"Expected >= {min_rows} data rows, got {len(rows)}")

            # Check no row has all-empty values
            empty_rows = sum(1 for r in rows if all(v.strip() == "" for v in r.values()))
            if empty_rows > 0:
                errors.append(f"{empty_rows} completely empty rows found")

    except Exception as e:
        errors.append(f"Failed to parse CSV: {e}")

    if errors:
        print(f"  [FAIL] {label or filepath}: {'; '.join(errors)}")
    else:
        print(f"  [OK]   {label or filepath}: {len(rows)} rows, columns {headers}")
    return len(errors) == 0


def run_test():
    # 1. Read existing env (to keep PATH, etc.)
    load_dotenv(os.path.join(os.path.dirname(__file__), "../.env"))
    env = os.environ.copy()

    # Check if key exists
    if not env.get("GEMINI_API_KEY"):
        print("ERROR: GEMINI_API_KEY not found in environment or ../.env!")
        sys.exit(1)

    # 2. Load .env-test manually to override
    print("Loading test configuration...")
    test_env_path = os.path.join(os.path.dirname(__file__), ".env-test")
    with open(test_env_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            key, val = line.split("=", 1)
            # Expand ${VAR} references from parent environment
            if val.startswith("${") and val.endswith("}"):
                ref_var = val[2:-1]
                val = os.environ.get(ref_var, "")
            env[key] = val

    # Verify critical vars
    print(f"Test Configuration:")
    print(f"  DOCS_DIR: {env.get('DOCS_DIR')}")
    print(f"  LLM_INPUT_DIR: {env.get('LLM_INPUT_DIR')}")
    print(f"  OUTPUT: {env.get('LLM_OUTPUT_FILE')}")

    # Setup Paths
    base_test_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.dirname(base_test_dir)
    inputs_dir = os.path.join(base_test_dir, "inputs_test")
    output_dir = os.path.join(base_test_dir, "output_test")
    os.makedirs(inputs_dir, exist_ok=True)
    os.makedirs(output_dir, exist_ok=True)

    # Generate Input PDF only if it doesn't exist
    pdf_path = os.path.join(inputs_dir, "test_doc.pdf")
    if not os.path.exists(pdf_path):
        generate_dummy_pdf(pdf_path)
    else:
        print(f"Using existing test PDF: {pdf_path}")

    # 3. Clean previous test outputs and intermediary files
    subprocess.run("rm -rf test/output_test/* test/chroma_db_test*", shell=True, cwd=root_dir)
    subprocess.run("rm -f test/inputs_test/*.md test/inputs_test/*.txt.ia test/inputs_test/*.ocr", shell=True, cwd=root_dir)
    subprocess.run("rm -f test/inputs_test/*.json test/inputs_test/*.dat", shell=True, cwd=root_dir)

    # 4. Run Pipeline as subprocess from ROOT
    print("\nRunning pipeline subprocess...")
    result = subprocess.run(
        [sys.executable, "pipeline.py"],
        env=env,
        cwd=root_dir,
        capture_output=False,
    )

    if result.returncode != 0:
        print("\n[FAIL] Pipeline exited with non-zero return code!")
        sys.exit(result.returncode)

    # 5. Assertions — file existence + content validation
    print("\nPipeline execution finished. Verifying artifacts...\n")

    all_passed = True

    # --- Step 0: PDF->MD conversion ---
    md_files = [f for f in os.listdir(inputs_dir) if f.endswith(".md")]
    if md_files:
        md_path = os.path.join(inputs_dir, md_files[0])
        size = os.path.getsize(md_path)
        if size > 0:
            print(f"  [OK]   PDF->MD conversion: {md_files[0]} ({size} bytes)")
        else:
            print(f"  [FAIL] PDF->MD conversion: {md_files[0]} is empty")
            all_passed = False
    else:
        print("  [FAIL] PDF->MD conversion: no .md file found in inputs_test/")
        all_passed = False

    # --- Step 1: Raw extraction (CSV with .json extension) ---
    f1 = os.path.join(root_dir, "test/output_test/1_raw_llm_extraction.json")
    if os.path.exists(f1):
        ok = validate_csv(f1, expected_columns=["Entity"], min_rows=1, label="Step 1 (extraction)")
        all_passed = all_passed and ok
    else:
        print("  [FAIL] Step 1 (extraction): file missing")
        all_passed = False

    # --- Step 2: Aggregated counts ---
    f2 = os.path.join(root_dir, "test/output_test/2_aggregated_counts.csv")
    if os.path.exists(f2):
        ok = validate_csv(f2, expected_columns=["Readable_Term", "Frequency"], min_rows=1, label="Step 2 (aggregation)")
        if ok:
            # Check frequencies are positive integers
            with open(f2, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                bad_freqs = [r for r in reader if not r["Frequency"].strip().isdigit() or int(r["Frequency"]) < 1]
                if bad_freqs:
                    print(f"  [FAIL] Step 2: {len(bad_freqs)} rows with invalid Frequency")
                    ok = False
        all_passed = all_passed and ok
    else:
        print("  [FAIL] Step 2 (aggregation): file missing")
        all_passed = False

    # --- Step 3: Filtered terms ---
    f3 = os.path.join(root_dir, "test/output_test/3_filtered_top_terms.csv")
    if os.path.exists(f3):
        ok = validate_csv(f3, expected_columns=["Readable_Term", "Frequency"], min_rows=1, label="Step 3 (filter)")
        all_passed = all_passed and ok
    else:
        print("  [FAIL] Step 3 (filter): file missing")
        all_passed = False

    # --- Step 4: NLD generation ---
    f4 = os.path.join(root_dir, "test/output_test/4_nld_generated_definitions.csv")
    if os.path.exists(f4):
        ok = validate_csv(f4, expected_columns=["Term", "NLD", "Context_Used", "Context"], min_rows=1, label="Step 4 (NLD)")
        if ok:
            # Check NLDs are not empty strings
            with open(f4, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                rows = list(reader)
                empty_nlds = [r for r in rows if not r.get("NLD", "").strip()]
                if empty_nlds:
                    print(f"  [WARN] Step 4: {len(empty_nlds)}/{len(rows)} terms have empty NLDs")
        all_passed = all_passed and ok
    else:
        print("  [FAIL] Step 4 (NLD): file missing")
        all_passed = False

    # --- Step 5: Categorization ---
    f5 = os.path.join(root_dir, "test/output_test/5_categorized_ontology.csv")
    if os.path.exists(f5):
        ok = validate_csv(
            f5,
            expected_columns=["Term", "RAG_Context_Used", "Category", "Reasoning", "NLD"],
            min_rows=1,
            label="Step 5 (categorization)",
        )
        if ok:
            # Check categories are not all ERROR
            with open(f5, "r", encoding="utf-8-sig") as f:
                reader = csv.DictReader(f)
                rows = list(reader)
                error_cats = [r for r in rows if r.get("Category", "").startswith("ERROR")]
                if error_cats and len(error_cats) == len(rows):
                    print(f"  [FAIL] Step 5: ALL {len(rows)} terms have ERROR categories")
                    ok = False
                elif error_cats:
                    print(f"  [WARN] Step 5: {len(error_cats)}/{len(rows)} terms have ERROR categories")
        all_passed = all_passed and ok
    else:
        print("  [FAIL] Step 5 (categorization): file missing")
        all_passed = False

    # --- Cross-step validation: term counts should be consistent ---
    print("\n--- Cross-step consistency checks ---")
    try:
        with open(f3, "r", encoding="utf-8-sig") as f:
            filtered_count = sum(1 for _ in csv.DictReader(f))
        with open(f4, "r", encoding="utf-8-sig") as f:
            nld_count = sum(1 for _ in csv.DictReader(f))
        with open(f5, "r", encoding="utf-8-sig") as f:
            cat_count = sum(1 for _ in csv.DictReader(f))

        if nld_count == filtered_count:
            print(f"  [OK]   Steps 3->4: filtered ({filtered_count}) == NLD ({nld_count})")
        else:
            print(f"  [WARN] Steps 3->4: filtered ({filtered_count}) != NLD ({nld_count})")

        if cat_count == nld_count:
            print(f"  [OK]   Steps 4->5: NLD ({nld_count}) == categorized ({cat_count})")
        else:
            print(f"  [WARN] Steps 4->5: NLD ({nld_count}) != categorized ({cat_count})")
    except Exception as e:
        print(f"  [WARN] Could not run cross-step checks: {e}")

    # --- Final verdict ---
    print()
    if all_passed:
        print("E2E Test Passed Successfully!")
    else:
        print("E2E Test Failed.")
        sys.exit(1)


if __name__ == "__main__":
    run_test()
