"""
OWL Exporter — Step 7 of the PreSaltOntoLearn pipeline.

Converts taxonomy CSV to a valid OWL ontology in Turtle format using rdflib.

Features:
  - Maps categories to published BFO/GeoCore/GeoReservoir IRIs
  - owl:Class + rdfs:subClassOf for classes
  - owl:NamedIndividual + rdf:type for individuals
  - rdfs:comment for NLDs, rdfs:label for readable names
  - Loadable in Protege
"""

import os
import re

import pandas as pd
from rdflib import Graph, Namespace, Literal, URIRef, RDF, RDFS, OWL, XSD

from src.utils import log

# Ontology namespace
ONTO_NS = Namespace("https://w3id.org/presalt-onto#")
BFO_NS = Namespace("http://purl.obolibrary.org/obo/")
GEOCORE_NS = Namespace("https://www.inf.ufrgs.br/bdi/ontologies/")
GEORESERVOIR_NS = Namespace("https://www.inf.ufrgs.br/bdi/ontologies/")

# Import the IRI mapping from taxonomy_builder
from src.modules.taxonomy_builder import UPPER_IRIS


def _term_to_iri(term: str) -> URIRef:
    """Convert a term string to a valid OWL IRI in the ontology namespace."""
    # Check if it's a known upper-level term
    if term in UPPER_IRIS:
        return URIRef(UPPER_IRIS[term])

    # Generate local IRI: CamelCase, no special chars
    local = re.sub(r"[^a-zA-Z0-9]", "_", term.strip())
    local = re.sub(r"_+", "_", local).strip("_")
    # CamelCase
    parts = local.split("_")
    camel = "".join(p.capitalize() for p in parts if p)
    return ONTO_NS[camel]


def run_owl_export(
    taxonomy_csv: str,
    nld_csv: str | None = None,
    output_path: str | None = None,
):
    """
    Export taxonomy to OWL Turtle format.

    Args:
        taxonomy_csv: Path to taxonomy CSV (output of taxonomy_builder)
        nld_csv: Optional path to NLD CSV (for adding definitions as rdfs:comment)
        output_path: Output .ttl path (default: derived from input)
    """
    if output_path is None:
        base = os.path.splitext(taxonomy_csv)[0]
        output_path = base.replace("6_taxonomy", "7_ontology") + ".ttl"

    df = pd.read_csv(taxonomy_csv, encoding="utf-8-sig")
    log.info(f"OWL Export: {len(df)} taxonomy entries from {taxonomy_csv}")

    # Load NLDs — primary source: NLD column in taxonomy CSV (added by taxonomy_builder)
    nld_map = {}
    if "NLD" in df.columns:
        for _, row in df.iterrows():
            nld_val = row.get("NLD", "")
            if nld_val and not pd.isna(nld_val):
                nld_map[str(row["Term"])] = str(nld_val)

    # Optional separate NLD CSV (fallback / override for backward compatibility)
    if nld_csv and os.path.exists(nld_csv):
        nld_df = pd.read_csv(nld_csv, encoding="utf-8-sig")
        for _, row in nld_df.iterrows():
            nld_map[row["Term"]] = row.get("NLD", "")

    # Build graph
    g = Graph()
    g.bind("owl", OWL)
    g.bind("rdf", RDF)
    g.bind("rdfs", RDFS)
    g.bind("presalt", ONTO_NS)
    g.bind("bfo", BFO_NS)
    g.bind("geocore", GEOCORE_NS)
    g.bind("georeservoir", GEORESERVOIR_NS)

    # Ontology declaration
    onto_uri = ONTO_NS["PreSaltOntoLearn"]
    g.add((onto_uri, RDF.type, OWL.Ontology))
    g.add((onto_uri, RDFS.label, Literal("PreSaltOntoLearn: Pre-Salt Petroleum Geology Ontology")))
    g.add((onto_uri, RDFS.comment, Literal(
        "A RAG-augmented LLM-generated ontology for Brazilian Pre-Salt petroleum geology. "
        "Generated by the PreSaltOntoLearn pipeline."
    )))

    # Import declarations
    g.add((onto_uri, OWL.imports, URIRef("http://purl.obolibrary.org/obo/bfo.owl")))

    # Process taxonomy entries
    for _, row in df.iterrows():
        term = row["Term"]
        parent = row["Parent_Term"]
        rel_type = row.get("Relationship_Type", "rdfs:subClassOf")
        is_intermediate = row.get("Is_Intermediate", False)

        term_iri = _term_to_iri(str(term))
        has_parent = parent and not (isinstance(parent, float) and pd.isna(parent)) and str(parent).strip()

        if has_parent:
            parent_iri = _term_to_iri(str(parent))
            if rel_type == "rdf:type":
                # Named individual
                g.add((term_iri, RDF.type, OWL.NamedIndividual))
                g.add((term_iri, RDF.type, parent_iri))
            else:
                # Class
                g.add((term_iri, RDF.type, OWL.Class))
                g.add((term_iri, RDFS.subClassOf, parent_iri))
        else:
            # Root node — declare as class with no explicit parent
            g.add((term_iri, RDF.type, OWL.Class))

        # Label
        g.add((term_iri, RDFS.label, Literal(term, lang="en")))

        # NLD as comment
        nld = nld_map.get(term, "")
        if nld and not str(nld).startswith("ERROR"):
            g.add((term_iri, RDFS.comment, Literal(str(nld), lang="en")))

        # Ensure parent class is also declared
        if parent not in UPPER_IRIS and not is_intermediate:
            g.add((parent_iri, RDF.type, OWL.Class))

    # Serialize
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    g.serialize(destination=output_path, format="turtle")

    # Stats
    n_classes = len(list(g.subjects(RDF.type, OWL.Class)))
    n_individuals = len(list(g.subjects(RDF.type, OWL.NamedIndividual)))
    n_triples = len(g)

    log.success(f"OWL ontology exported: {output_path}")
    log.detail(f"Classes: {n_classes}, Individuals: {n_individuals}, Triples: {n_triples}")
    log.detail(f"Format: Turtle (.ttl) — open in Protege to verify")

    return output_path


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("taxonomy_csv", help="Path to taxonomy CSV")
    parser.add_argument("--nld", default=None, help="Path to NLD CSV for adding definitions")
    parser.add_argument("--output", default=None, help="Output .ttl path")
    args = parser.parse_args()
    run_owl_export(args.taxonomy_csv, args.nld, args.output)
