"""
OWL Exporter — Step 7 of the PreSaltOntoLearn pipeline.

Converts taxonomy CSV to a valid OWL ontology in Turtle format using rdflib.

Features:
  - Maps categories to published BFO/GeoCore/GeoReservoir IRIs
  - owl:Class + rdfs:subClassOf for classes
  - owl:NamedIndividual + rdf:type for individuals
  - rdfs:comment for NLDs, rdfs:label for readable names
  - Loadable in Protege
"""

import os
import re

import pandas as pd
from rdflib import BNode, Graph, Namespace, Literal, URIRef, RDF, RDFS, OWL, XSD

from src.utils import log

# Ontology namespace
ONTO_NS = Namespace("https://w3id.org/presalt-onto#")
BFO_NS = Namespace("http://purl.obolibrary.org/obo/")
GEOCORE_NS = Namespace("https://www.inf.ufrgs.br/bdi/ontologies/")
GEORESERVOIR_NS = Namespace("https://www.inf.ufrgs.br/bdi/ontologies/")

# Import the IRI mapping from taxonomy_builder
from src.modules.taxonomy_builder import UPPER_IRIS

# Build case-insensitive lookup for UPPER_IRIS
_UPPER_IRIS_LOWER = {k.lower(): v for k, v in UPPER_IRIS.items()}


def _term_to_iri(term: str) -> URIRef:
    """Convert a term string to a valid OWL IRI in the ontology namespace."""
    # Case-insensitive check against known upper-level terms
    term_lower = term.strip().lower()
    if term_lower in _UPPER_IRIS_LOWER:
        return URIRef(_UPPER_IRIS_LOWER[term_lower])

    # Generate local IRI: CamelCase from lowercased input to avoid case collisions
    local = re.sub(r"[^a-zA-Z0-9]", "_", term.strip().lower())
    local = re.sub(r"_+", "_", local).strip("_")
    # CamelCase
    parts = local.split("_")
    camel = "".join(p.capitalize() for p in parts if p)
    return ONTO_NS[camel]


def run_owl_export(
    taxonomy_csv: str,
    nld_csv: str | None = None,
    output_path: str | None = None,
    relations_csv: str | None = None,
):
    """
    Export taxonomy to OWL Turtle format.

    Args:
        taxonomy_csv: Path to taxonomy CSV (output of taxonomy_builder)
        nld_csv: Optional path to NLD CSV (for adding definitions as rdfs:comment)
        output_path: Output .ttl path (default: derived from input)
    """
    if output_path is None:
        base = os.path.splitext(taxonomy_csv)[0]
        output_path = base.replace("6_taxonomy", "7_ontology") + ".ttl"

    df = pd.read_csv(taxonomy_csv, encoding="utf-8-sig")
    log.info(f"OWL Export: {len(df)} taxonomy entries from {taxonomy_csv}")

    # Load NLDs — primary source: NLD column in taxonomy CSV (added by taxonomy_builder)
    nld_map = {}
    if "NLD" in df.columns:
        for _, row in df.iterrows():
            nld_val = row.get("NLD", "")
            if nld_val and not pd.isna(nld_val):
                nld_map[str(row["Term"])] = str(nld_val)

    # Optional separate NLD CSV (fallback / override for backward compatibility)
    if nld_csv and os.path.exists(nld_csv):
        nld_df = pd.read_csv(nld_csv, encoding="utf-8-sig")
        for _, row in nld_df.iterrows():
            nld_map[row["Term"]] = row.get("NLD", "")

    # Build graph
    g = Graph()
    g.bind("owl", OWL)
    g.bind("rdf", RDF)
    g.bind("rdfs", RDFS)
    g.bind("presalt", ONTO_NS)
    g.bind("bfo", BFO_NS)
    g.bind("geocore", GEOCORE_NS)
    g.bind("georeservoir", GEORESERVOIR_NS)

    # Ontology declaration
    onto_uri = ONTO_NS["PreSaltOntoLearn"]
    g.add((onto_uri, RDF.type, OWL.Ontology))
    g.add((onto_uri, RDFS.label, Literal("PreSaltOntoLearn: Pre-Salt Petroleum Geology Ontology")))
    g.add((onto_uri, RDFS.comment, Literal(
        "A RAG-augmented LLM-generated ontology for Brazilian Pre-Salt petroleum geology. "
        "Generated by the PreSaltOntoLearn pipeline."
    )))

    # Import declarations
    g.add((onto_uri, OWL.imports, URIRef("http://purl.obolibrary.org/obo/bfo.owl")))

    # Process taxonomy entries
    for _, row in df.iterrows():
        term = row["Term"]
        parent = row["Parent_Term"]
        rel_type = row.get("Relationship_Type", "rdfs:subClassOf")
        is_intermediate = row.get("Is_Intermediate", False)

        term_iri = _term_to_iri(str(term))
        has_parent = parent and not (isinstance(parent, float) and pd.isna(parent)) and str(parent).strip()

        if has_parent:
            parent_iri = _term_to_iri(str(parent))
            if rel_type == "rdf:type":
                # Named individual
                g.add((term_iri, RDF.type, OWL.NamedIndividual))
                g.add((term_iri, RDF.type, parent_iri))
            elif term_iri != parent_iri:
                # Class — guard against self-referential subClassOf
                g.add((term_iri, RDF.type, OWL.Class))
                g.add((term_iri, RDFS.subClassOf, parent_iri))
            else:
                # Self-reference detected (case collision) — declare as class only
                g.add((term_iri, RDF.type, OWL.Class))
        else:
            # Root node — declare as class with no explicit parent
            g.add((term_iri, RDF.type, OWL.Class))

        # Label
        g.add((term_iri, RDFS.label, Literal(term, lang="en")))

        # NLD as comment
        nld = nld_map.get(term, "")
        if nld and not str(nld).startswith("ERROR"):
            g.add((term_iri, RDFS.comment, Literal(str(nld), lang="en")))

        # Ensure parent class is also declared
        if parent not in UPPER_IRIS and not is_intermediate:
            g.add((parent_iri, RDF.type, OWL.Class))

    # Add rdfs:label for all upper-level IRIs referenced in the graph
    _upper_label_map = {v: k for k, v in UPPER_IRIS.items()}
    _labeled_uppers = set()
    for _, _, o in list(g.triples((None, RDFS.subClassOf, None))):
        o_str = str(o)
        if o_str in _upper_label_map and o_str not in _labeled_uppers:
            g.add((URIRef(o_str), RDF.type, OWL.Class))
            g.add((URIRef(o_str), RDFS.label, Literal(_upper_label_map[o_str], lang="en")))
            _labeled_uppers.add(o_str)
    for _, _, o in list(g.triples((None, RDF.type, None))):
        o_str = str(o)
        if o_str in _upper_label_map and o_str not in _labeled_uppers:
            g.add((URIRef(o_str), RDF.type, OWL.Class))
            g.add((URIRef(o_str), RDFS.label, Literal(_upper_label_map[o_str], lang="en")))
            _labeled_uppers.add(o_str)

    # ── Relation restrictions (Step 6b) ──
    n_restrictions = 0
    if relations_csv and os.path.exists(relations_csv):
        rel_df = pd.read_csv(relations_csv, encoding="utf-8-sig")
        accepted = rel_df[rel_df["Validation_Status"] == "ACCEPTED"]
        log.info(f"Adding {len(accepted)} relation restrictions from {relations_csv}")

        # Declare used object properties
        declared_props = set()
        for _, rel in accepted.iterrows():
            prop_iri_str = rel.get("Property_IRI", "")
            prop_name = rel.get("Property", "")
            if prop_iri_str and prop_iri_str not in declared_props:
                prop_uri = URIRef(prop_iri_str)
                g.add((prop_uri, RDF.type, OWL.ObjectProperty))
                g.add((prop_uri, RDFS.label, Literal(prop_name.replace("_", " "), lang="en")))
                declared_props.add(prop_iri_str)

        # Add existential restrictions: Class ⊑ ∃property.Filler
        for _, rel in accepted.iterrows():
            term_iri = _term_to_iri(str(rel["Term"]))
            filler_iri = _term_to_iri(str(rel["Filler"]))
            prop_iri_str = rel.get("Property_IRI", "")
            if not prop_iri_str:
                continue

            prop_uri = URIRef(prop_iri_str)

            # Ensure filler is declared as a class
            g.add((filler_iri, RDF.type, OWL.Class))

            # BNode restriction: term ⊑ ∃property.filler
            restriction = BNode()
            g.add((restriction, RDF.type, OWL.Restriction))
            g.add((restriction, OWL.onProperty, prop_uri))
            g.add((restriction, OWL.someValuesFrom, filler_iri))
            g.add((term_iri, RDFS.subClassOf, restriction))
            n_restrictions += 1

    # ── BFO disjointness axioms (safe only) ──
    _BFO_DISJOINT = [
        ("http://purl.obolibrary.org/obo/BFO_0000002", "http://purl.obolibrary.org/obo/BFO_0000003"),  # Continuant ⊥ Occurrent
        ("http://purl.obolibrary.org/obo/BFO_0000004", "http://purl.obolibrary.org/obo/BFO_0000020"),  # IC ⊥ SDC
        ("http://purl.obolibrary.org/obo/BFO_0000004", "http://purl.obolibrary.org/obo/BFO_0000031"),  # IC ⊥ GDC
        ("http://purl.obolibrary.org/obo/BFO_0000020", "http://purl.obolibrary.org/obo/BFO_0000031"),  # SDC ⊥ GDC
        ("http://purl.obolibrary.org/obo/BFO_0000040", "http://purl.obolibrary.org/obo/BFO_0000141"),  # MaterialEntity ⊥ ImmaterialEntity
    ]
    if n_restrictions > 0:
        for iri_a, iri_b in _BFO_DISJOINT:
            g.add((URIRef(iri_a), OWL.disjointWith, URIRef(iri_b)))
        log.detail(f"Added {len(_BFO_DISJOINT)} BFO disjointness axioms")

    # Serialize
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    g.serialize(destination=output_path, format="turtle")

    # Stats
    n_classes = len(list(g.subjects(RDF.type, OWL.Class)))
    n_individuals = len(list(g.subjects(RDF.type, OWL.NamedIndividual)))
    n_triples = len(g)

    log.success(f"OWL ontology exported: {output_path}")
    log.detail(f"Classes: {n_classes}, Individuals: {n_individuals}, Triples: {n_triples}")
    if n_restrictions > 0:
        log.detail(f"Existential restrictions: {n_restrictions}")
    log.detail(f"Format: Turtle (.ttl) — open in Protege to verify")

    return output_path


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("taxonomy_csv", help="Path to taxonomy CSV")
    parser.add_argument("--nld", default=None, help="Path to NLD CSV for adding definitions")
    parser.add_argument("--output", default=None, help="Output .ttl path")
    parser.add_argument("--relations", default=None, help="Path to 6b_relations.csv")
    args = parser.parse_args()
    run_owl_export(args.taxonomy_csv, args.nld, args.output, args.relations)
